### ISSUE TITLE
how does this work?

### ISSUE THREAD

**Issue by anarcat** [spanezz/siterefactor#1]
I'm looking at converting my ikiwiki site into... something else. Maybe staticsite, but i'm also seriously considering hugo as I use it in other projets.

I've tried to convert https://anarc.at/ using this, therefore. It seems like it has a few rough edges, for example I have my tags in the `tag/` directory and that makes siterefactor quite unhappy:

```
anarcat@angela:anarc.at$ ~/dist/siterefactor/siterefactor -v . ../anarc.at-hugo
2023-03-10 15:09:55,105 INFO Loading tag info from tags
Traceback (most recent call last):
  File "/home/anarcat/dist/siterefactor/siterefactor", line 85, in <module>
    main()
  File "/home/anarcat/dist/siterefactor/siterefactor", line 36, in main
    site.read_tag_descriptions("tags")
  File "/home/anarcat/dist/siterefactor/siterefactorlib/core.py", line 289, in read_tag_descriptions
    for f in os.listdir(abspath):
             ^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/anarcat/wikis/anarc.at/tags'
```

a symlink works around that issue, but then it's somewhat unhappy with my tag pages:

```
anarcat@angela:anarc.at$ ~/dist/siterefactor/siterefactor -v -t hugo . ../anarc.at-hugo
2023-03-10 15:10:34,654 INFO Loading tag info from tags
2023-03-10 15:10:34,654 WARNING tags/politique.mdwn: found unsupported tag lookup: [[!meta title="pages tagged politique"]]
2023-03-10 15:10:34,654 WARNING tags/politique.mdwn: found unsupported tag lookup: [[!inline pages="tagged(politique)" actions="no" archive="yes"
2023-03-10 15:10:34,654 WARNING tags/gitlab.mdwn: found unsupported tag lookup: [[!meta title="pages tagged gitlab"]]
2023-03-10 15:10:34,654 WARNING tags/gitlab.mdwn: found unsupported tag lookup: [[!inline pages="tagged(gitlab)" actions="no" archive="yes"
2023-03-10 15:10:34,654 WARNING tags/shit.mdwn: found unsupported tag lookup: [[!meta title="pages tagged shit"]]
2023-03-10 15:10:34,654 WARNING tags/shit.mdwn: found unsupported tag lookup: [[!inline pages="tagged(shit)" actions="no" archive="yes"
2023-03-10 15:10:34,654 WARNING tags/terminals.mdwn: found unsupported tag lookup: [[!meta title="pages tagged terminals"]]
2023-03-10 15:10:34,654 WARNING tags/terminals.mdwn: found unsupported tag lookup: [[!inline pages="tagged(terminals)" actions="no" archive="yes"
2023-03-10 15:10:34,654 WARNING tags/sieve.mdwn: found unsupported tag lookup: [[!meta title="pages tagged sieve"]]
2023-03-10 15:10:34,654 WARNING tags/sieve.mdwn: found unsupported tag lookup: [[!inline pages="tagged(sieve)" actions="no" archive="yes"
[...]
2023-03-10 15:10:34,683 WARNING tags/usability.mdwn: found unsupported tag lookup: [[!meta title="pages tagged usability"]]
2023-03-10 15:10:34,683 WARNING tags/usability.mdwn: found unsupported tag lookup: [[!inline pages="tagged(usability)" actions="no" archive="yes"
anarcat@angela:anarc.at$ 
```

... and then it basically does nothing from there. it doesn't create the output dir, nor does the `-t dump` argument help me in any way:

```
Traceback (most recent call last):
  File "/home/anarcat/dist/siterefactor/siterefactor", line 85, in <module>
    main()
  File "/home/anarcat/dist/siterefactor/siterefactor", line 80, in main
    writer.write(site)
  File "/home/anarcat/dist/siterefactor/siterefactorlib/dump.py", line 55, in write
    for static in site.static.values():
                  ^^^^^^^^^^^
AttributeError: 'Site' object has no attribute 'static'
```

should i be using this at all?

thanks!

**Comment by spanezz** [comment]
> should i be using this at all?

It was code I used to migrate my blog, I hacked on it until it worked for me and at that point I had no need for it anymore.

I guess you could use it as a base or as a collection of code to steal from, rather than as a finished product. It's been years but looking at those error messages I would imagine I used some pattern matching for the expressions I used in my ikiwiki sources, and didn't implement support for all of ikiwiki
